config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'basics', to: 'users/registrations#new_basic'
    post 'basics', to: 'users/registrations#create_basic'
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end

  resources :users do
    resource :profiles, only: [:edit, :update, :show]
  end

  root to: 'tops#index'
end

app/views/layouts/_footer.html.haml
%footer
  .footer__inner
    %ul.footer__menu
      %li.footer__menu__column
        %p.footer__menu__title About
        %ul.footer__menu__list
          %li.footer__menu__item
            = link_to "運営者サイト", "https://kyantaro-man.github.io/shin_portfolio_site/", class: "link white"
          %li.footer__menu__item
            = link_to "利用規約", "#", class: "link white"
          %li.footer__menu__item
            = link_to "ヘルプ", "#", class: "link white"
          %li.footer__menu__item
            = link_to "プライバシー", "#", class: "link white"
      %li.footer__menu__column
        %p.footer__menu__title Products
        %ul.footer__menu__list
          %li.footer__menu__item
            = link_to "https://myselfnote.herokuapp.com/", class: "link white" do
              MySelf
              %p.footer__menu__item-description 日記アプリです。自己紹介文も記録できます。(Herokuデプロイ)
          %li.footer__menu__item
            = link_to "https://chatbot-shin.web.app/", class: "link white" do
              ChatBotShin
              %p.footer__menu__item-description チャットボットアプリです。Reactの勉強用で作成しました。(firebaseデプロイ)
    .footer__bottom
      .footer__bottom-logo
        = link_to image_tag("/assets/title-logo.png", alt: "フッターロゴ画像", height: "44px", class: ""), root_path, data: {turbolinks: false}
      .footer__bottom-text
        = link_to "トップへ戻る", "", class: "link white", data: {turbolinks: false}

app/views/layouts/_header.html.haml
%header
  - if user_signed_in?
    = link_to image_tag("/assets/header-logo.png", alt: "ヘッダーロゴ画像", height: "44px", width: "44px", class: "header__logo"), root_path
    %nav.global-menu
      %ul.global-menu__box
        %li.grobal-menu__item
          = link_to "おすすめ/人気を探す", root_path, class: "link"
        %li.global-menu__item
          = link_to "自己分析をする", "#", class: "link"
    = form_with local: true, class: "search-form" do |f|
      = f.text_field :keyword, class: "search-form__input", placeholder: "ユーザー名でプロフィールを検索"
      = icon("fas", "search", class: "search-form__icon")
    %nav.user-menu
      %ul.user-menu__box
        %li.user-menu__item
          = icon("fas", "heart")
        %li.user-menu__item
          = icon("fas", "edit")
    .user-profile
      - if current_user.id == @user.id
        = link_to "", class: "js-user-profile__link" do
          .user-profile__image{style: "background-image: url(#{@profile.profile_image.url})"}
      - else
        - @user = User.find(current_user.id)
        - @profile = @user.profile
        = link_to "", class: "js-user-profile__link" do
          .user-profile__image{style: "background-image: url(#{@profile.profile_image.url})"}
        - @user = User.find(params[:user_id])
        - @profile = @user.profile
      %ul.user-profile__text
        %li
          = @user.nickname
        %li 
          = @user.username
  - else
    = link_to image_tag("/assets/title-logo.png", alt: "ヘッダーロゴ画像", height: "44px", class: ""), root_path
    %nav.authentication-menu
      %ul.authentication-menu__box
        %li.authentication-menu__item
          = link_to "ログインする", new_user_session_path, class: "authentication-menu__link"
        %li.authentication-menu__item
          = link_to "新規登録する", new_user_registration_path, class: "authentication-menu__link"
%ul.usermenu
  %li.usermenu-item
    = link_to "プロフィール編集ページへ", edit_user_profiles_path(current_user.id), data: {turbolinks: false}
  %li.usermenu-item
    = link_to "プロフィールページへ", user_profiles_path(current_user.id), data: {turbolinks: false}
  %li.usermenu-item
    = link_to "ユーザー情報編集ページへ", edit_user_registration_path
  %li.usermenu-item
    = link_to "いいねページへ"
  %li.usermenu-item
    = link_to "13のプロフィールへ", user_profiles_path(13), data: {turbolinks: false}

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Findself
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield